
from typing import List
from venv import logger
from langchain_openai import OpenAI
from ragas import SingleTurnSample
from app.api.testing.retrieval_metrics.context_precisions import ContextPrecisionEvaluator
from app.api.testing.retrieval_metrics.context_recall import ContextRecallEvaluator
from app.api.testing.retrieval_metrics.context_relevance import ContextRelevancelEvaluator
from app.api.testing.generation_metrics.groundedness import ResponseGroundednessEvaluator
from app.api.testing.generation_metrics.answer_semantic_similarity import SemanticSimilarityEvaluator
from app.api.testing.generation_metrics.answer_relevance import AnswerRelevanceEvaluator

class Evaluator:
    def __init__(self, llm: OpenAI):
        self.context_precision = ContextPrecisionEvaluator(evaluator_llm=llm)
        self.context_recall = ContextRecallEvaluator(evaluator_llm=llm)
        self.context_relevance = ContextRelevancelEvaluator(evaluator_llm=llm)
        self.groundedness = ResponseGroundednessEvaluator(evaluator_llm=llm)
        self.semantic_similarity = SemanticSimilarityEvaluator(evaluator_llm=llm)
        self.answer_relevance = AnswerRelevanceEvaluator(evaluator_llm=llm)

        self.samples = List[SingleTurnSample]
    def add_sample(self, user_input: str, response: str, retrieved_contexts: list, reference: str):
        """
        Add a sample to the evaluator.
        :param user_input: The user's input question.
        :param response: The response generated by the system.
        :param retrieved_contexts: The list of retrieved contexts.
        :param reference: The reference answer for the question.
        """
        self.samples.append(SingleTurnSample(
            user_input=user_input,
            response=response,
            retrieved_contexts=retrieved_contexts,
            reference=reference
        ))

    async def evaluate_sample(self, sample: SingleTurnSample):
        """
        Evaluate a single sample.
        :param sample: The sample to evaluate.
        """
        logger.info(f"Evaluating sample: {sample}")

        await self.context_precision.evaluate(sample)
        await self.context_recall.evaluate(sample)
        await self.context_relevance.evaluate(sample)
        await self.groundedness.evaluate(sample)
        await self.semantic_similarity.evaluate(sample)
        await self.answer_relevance.evaluate(sample)
        logger.info(f"Evaluation completed for sample: {sample}")
    
    async def evaluate_samples(self):
        for sample in self.samples:
            # Evaluate the context precision for each sample
            await self.evaluate_sample(sample)
            
            
            