from langchain_openai import OpenAI
from typing import List
from ragas import SingleTurnSample
from ragas.metrics import SemanticSimilarity
from config import logger


class SemanticSimilarityEvaluator:
    def __init__(self, evaluator_llm: OpenAI):
        """
        Initialize the evaluator with an LLM model.
        :param evaluator_llm: LLM model to use for evaluation.
        """
        self.context_precision = SemanticSimilarity(llm=evaluator_llm)

    async def evaluate(self, sample: SingleTurnSample): 
        """
        Evaluate the semantic similarity for a single sample.
        :param user_input: The user's input question.
        :param response: The response generated by the system.
        :param retrieved_contexts: The list of retrieved contexts.
        :return: The semantic similarity score.
        """
        score = await self.context_precision.single_turn_ascore(sample)
        logger.info(f"Semantic similarity Score: {score}")