from langchain_openai import OpenAI
from typing import List
from ragas import SingleTurnSample
from ragas.metrics import LLMContextRecall
from config import logger


class ContextRecallEvaluator:
    def __init__(self, evaluator_llm: OpenAI):
        """
        Initialize the evaluator with an LLM model.
        :param evaluator_llm: LLM model to use for evaluation.
        """
        self.context_recall = LLMContextRecall(llm=evaluator_llm)

    async def evaluate(self, sample: SingleTurnSample): 
        """
        Evaluate the context recall for a single sample.
        :param user_input: The user's input question.
        :param response: The response generated by the system.
        :param retrieved_contexts: The list of retrieved contexts.
        :return: The context recall score.
        """
        score = await self.context_recall.single_turn_ascore(sample)
        logger.info(f"Context Recall Score: {score}")